{"level":50,"time":"15-Jan-2023 17:49:44 044","pid":5264,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"TypeError","message":"Cannot destructure property 'username' of 'req.body' as it is undefined.","stack":"TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:7:17\n    at Generator.next (<anonymous>)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:4:12)\n    at createUser (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:78)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)"},"msg":"Cannot destructure property 'username' of 'req.body' as it is undefined."}
{"level":50,"time":"15-Jan-2023 17:50:26 026","pid":2860,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"TypeError","message":"Cannot destructure property 'username' of 'req.body' as it is undefined.","stack":"TypeError: Cannot destructure property 'username' of 'req.body' as it is undefined.\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:9:17\n    at Generator.next (<anonymous>)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:4:12)\n    at createUser (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:78)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)"},"msg":"Cannot destructure property 'username' of 'req.body' as it is undefined."}
{"level":50,"time":"15-Jan-2023 17:59:27 027","pid":18656,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Not found","stack":"Error: Not found\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\app.ts:19:10\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)","statusCode":404},"msg":"Not found"}
{"level":50,"time":"15-Jan-2023 17:59:29 029","pid":18656,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Not found","stack":"Error: Not found\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\app.ts:19:10\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)","statusCode":404},"msg":"Not found"}
{"level":50,"time":"15-Jan-2023 18:01:58 058","pid":4448,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Not found","stack":"Error: Not found\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\app.ts:19:10\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at processImmediate (node:internal/timers:468:21)","statusCode":404},"msg":"Not found"}
{"level":50,"time":"15-Jan-2023 18:02:17 017","pid":3420,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Password must be greater than 4","stack":"Error: Password must be greater than 4\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:19:25\n    at Generator.next (<anonymous>)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:4:12)\n    at createUser (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:6:78)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)","statusCode":400},"msg":"Password must be greater than 4"}
{"level":50,"time":"15-Jan-2023 18:14:48 048","pid":13500,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:17:30 030","pid":15324,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:18:58 058","pid":12716,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:18:58 058","pid":12716,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:22:06 006","pid":13412,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:23:35 035","pid":6456,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:24:27 027","pid":7084,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:25:15 015","pid":13952,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:25:33 033","pid":12424,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:26:05 005","pid":10028,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:26:05 005","pid":10028,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:26:33 033","pid":4592,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:26:34 034","pid":4592,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:33:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:29:26 026","pid":3700,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:40:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:29:43 043","pid":13640,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:40:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:31:22 022","pid":20072,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:40:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:31:22 022","pid":20072,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Password must be greater than 4","stack":"Error: Password must be greater than 4\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:19:25\n    at Generator.next (<anonymous>)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:4:12)\n    at createUser (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:6:78)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)","statusCode":400},"msg":"Password must be greater than 4"}
{"level":50,"time":"15-Jan-2023 18:32:37 037","pid":15552,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"User already exist","stack":"Error: User already exist\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:40:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","statusCode":400},"msg":"User already exist"}
{"level":50,"time":"15-Jan-2023 18:32:37 037","pid":15552,"hostname":"MSI","name":"UNIT-TEST","err":{"type":"ApiError","message":"Password must be greater than 4","stack":"Error: Password must be greater than 4\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:19:25\n    at Generator.next (<anonymous>)\n    at C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:4:12)\n    at createUser (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\app\\modules\\users\\v1\\controller.ts:6:78)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\shaha\\OneDrive\\Desktop\\Shahabaz\\projects\\unit-testing\\node_modules\\express\\lib\\router\\layer.js:95:5)","statusCode":400},"msg":"Password must be greater than 4"}
